- README.md
changed 
timetk.data.load_dataset('bike_sales_sample') 
to 
timetk.datasets.load_dataset('bike_sales_sample')
> readme_datasets_path_fix

- src/timetk/__init__.py
- src/timetk/plot/__init__.py
- src/timetk/plot/plot_time_series.py
Hi Matt, this code is not done yet. 
I create the function and the `__init__`. It is working for a single time series and a grouped time series.
The issue is about the `scale_x_datetime` when I set `scale = free` in `facet_wrap`.
> [feat]: create plot_time_series

- tests/test_load_dataset.py
Added additional datasets to test
- m4_quarterly
- m4_yearly
- bike_sales_sample
- bike_sharing_daily
- taylor_30_min
- walmart_sales_weekly
- wikipedia_traffic_daily
> Added  remaining datasets to test_load_dataset

- tests/test_future_frame.py
Issue #28 - pt2. tk.future_frame() test
https://github.com/business-science/pytimetk/issues/28
> Issue #28 - pt2. tk.future_frame() test

- tests/test_pad_by_time.py
Tests: Data Wrangling Functions #28
part 3:  pad by time
> issue#28 - pad by time test

- docs/guides/01_visualization.qmd
I created the documentation for `plot_timeseries()` to include it on https://business-science.github.io/pytimetk/
I didn't include the freezes and the index because I was worried about potentially messing up the website.  I believe it's safer for you to run the documentation on your end.
> [docs]: created plot_timeseries visualization

- docs/guides/05_augmenting.qmd
Added some examples examples for `augment_lags`, `augment_leads` and `augment_rolling`.
> guides: agument_leads, augment_lags, agument_rolling

- tests/test_ts_summary.py
Tests: tk.ts_summary() #35
Created tests for ts_summary:
- Regular DF
- Grouped DF
- Checks for inputs & outputs
> test ts_summary issue 35

- tests/test_plot_timeseries.py
Tests: plot_timeseries() #39
Added tests for plot_timeseries using multiple engines:
- plotly
- plotnine
- matplotlib
> Tests: plot_timeseries() #39 - Iniitial batch of tests

- tests/test_holiday_signature.py
Tests: Augment Functions #27 task 2
- Tests for Augment Holiday Signature
> Tests: Augment Functions #27 task 2 - Augment holiday signature

- tests/test_lags.py
Tests: Augment Functions #27 task 3 - augment_lags
> Tests: Augment Functions #27 task 3 - augment_lags

- tests/test_leads.py
Tests: Augment Functions #27 Task 4
Added Augment leads test
> Tests: Augment Functions #27 - Task 4 Augment leads

- tests/test_rolling.py
Tests: Augment Functions #27 Task 5
Test Augment Rolling
> Tests: Augment Functions #27 Task 5 - Augment Rolling

- src/pytimetk/__init__.py
- src/pytimetk/core/__init__.py
- src/pytimetk/core/expanding.py
Added augment_expanding functionality. Looks to be working on the initial examples. I will continue to test.
> Introduce augment_expanding function in a new expanding.py file

- docs/guides/05_augmenting.qmd
**Adding examples for `augment_fourier()`**
> Augment guide

- docs/tutorials/03_demand_forecasting.qmd
Cleaned up the code.
- Removed the creation of several dummy variables
- Added functions such as tk.augment_lags, tk.augment_rolling
- Simplified code structure to focus more on the functions rather than complicated python code.
Future Enhancements
- Add tk.augment_fourier once the function is adapted to R style.
- Add in Holidays when we change holiday function to adapt to weekly data.
> Applied Tutorial: Demand Forecasting #48 - Cleanup

- src/pytimetk/finance/__init__.py
- src/pytimetk/finance/exponential.py
- New Subfolder: Introduces a finance subfolder.
- Functionality: Adds the augment_ewm function in exponential.py
Provides string-based access to built-in pandas EWM functions and augments to data frame.
> feat(finance): add augment_ewm function

- src/pytimetk/core/expanding.py
- Consolidated data verification steps within the primary function to reduce code redundancy.
- Modified the Polars selection approach: switched from `df.select(expression.over())` to the faster `df.groupby().agg(expressions)`
> Further speedup for polars backend in the augment_expanding function

- src/pytimetk/core/timeseries_signature.py
This is a fairly extensive refactor. 
1. It makes the original versions more efficient by streamlining the feature creation and naming by doing this more directly. This also makes it more readable. 
2. These original versions, both `augment_timeseries_signature` and `get_timeseries_signature` were converted into `_augment_timeseries_signature_pandas` and `_get_timeseries_signature_pandas`. 
3. New `_augment_timeseries_signature_polars` and `_get_timeseries_signature_polars` were added.
4. Finally, new engine-basaed wrapper functions `augment_timeseries_signature` and `get_timeseries_signature` were created to control backend usage.
> Major refactor of 'timeseries_signature' functions

- src/pytimetk/utils/datetime_helpers.py
Simplified, mapped dict, made more extendable.
> freq_to_timedelta

- src/pytimetk/core/expanding.py
- src/pytimetk/core/rolling.py
- Added Polars backend support
- Examples in the docu-string were NOT updated yet
> feat(augment_rolling): Add polars backend support

- src/pytimetk/core/anomalize.py
- src/pytimetk/core/apply_by_time.py
Just simple clean up of docstring to make more readable and align with PEP8
> apply_by_time docstring PEP8

- src/pytimetk/core/expanding.py
Just corrected docstring formatting to align with PEP8 making it easier for users to read.
> expanding docstring PEP8 

- src/pytimetk/core/frequency.py
Just aligning frequency docstring PEP8
> frequency docstring PEP8

- src/pytimetk/core/future.py
- src/pytimetk/core/holiday_signature.py
> holiday docstring pep8 

- src/pytimetk/core/future.py
- src/pytimetk/core/lags.py
- src/pytimetk/core/leads.py
- src/pytimetk/core/make_timeseries_sequence.py
- src/pytimetk/core/pad.py
Aligned future docstring with PEP8, making it more readable
> future docstring PEP8

- src/pytimetk/core/rolling.py
> Update rolling.py docstring pep8

- src/pytimetk/core/summarize_by_time.py
- src/pytimetk/core/timeseries_signature.py
summarize_by_time docstring pep8
> summarize_by_time docstring pep8

- src/pytimetk/core/ts_features.py
> Update ts_features.py docstring pep8

- src/pytimetk/core/ts_summary.py
> ts_features.py-docstring-pep8

- src/pytimetk/finance/exponential.py
- src/pytimetk/plot/plot_anomalies.py
- src/pytimetk/plot/plot_anomaly_decomp.py
- src/pytimetk/plot/plot_timeseries.py
- src/pytimetk/plot/theme.py
- src/pytimetk/utils/datetime_helpers.py
datetime helpers.py docstring pep8
> datetime helpers.py docstring pep8

- src/pytimetk/finance/exponential.py
- src/pytimetk/plot/plot_anomalies.py
- src/pytimetk/plot/plot_anomaly_decomp.py
- src/pytimetk/plot/plot_timeseries.py
- src/pytimetk/plot/theme.py
- src/pytimetk/utils/pandas_helpers.py
- src/pytimetk/utils/parallel_helpers.py
> ewm - docstring pep8

- src/pytimetk/datasets/get_datasets.py
> get_data docstring pep8

- src/pytimetk/datasets/get_datasets.py
Added a polars engine to load data faster.
> Added polars engine to load data faster! 

- src/pytimetk/core/make_timeseries_sequence.py
Completed `make_weekday_sequence` polars backend
> make_weekday_sequence polars engine

- src/pytimetk/utils/datetime_helpers.py
Not a massive speed gain, but I imagine for a longer date range it could shave off a bit of time. Regardless it is just providing the consistency across all the of the functions.
> is_holiday polars backend

- src/pytimetk/core/ts_summary.py
get_date_summary polars backend
> get_date_summary polars backend

- src/pytimetk/core/fourier.py
creating the pull request, still a work in progress
solves #22
> first work

- docs/reference/is_holiday.qmd
timeseries_unit_get_frequency_table polars
This also has some of the qmd changes that will obviously be overwritten but there are no conflicts here.
> timeseries_unit_get_frequency_table polars

- src/pytimetk/__init__.py
- src/pytimetk/core/__init__.py
Updated Core and pytimetk _init_ files with the hilbert module.
> updated _init_ for hilbert transform

- docs/reference/is_holiday.qmd
- src/pytimetk/core/frequency.py
frequency.py time_scale_template - polars
> frequency.py time_scale_template - polars

- src/pytimetk/feature_engineering/hilbert.py
Fixed the following bugs and additions 
1. Original dataframe was not being returned with polars engine.
2. Added 2 additional examples for non-grouped dataframes.
3. Fixed an issue with the polars engine where it wasnt properly handling non-groupby objects.
> #176 hilert bug fix return original data

- src/pytimetk/feature_engineering/holiday_signature.py
add countries format docstring
> Update holiday_signature.py add countries format docstring

- src/pytimetk/utils/pandas_helpers.py
This was quite annoying. Polars has a glimpse, but because the dtypes are different I had to solve a few quirky things. Also while doing it I noticed some inefficiencies in the current glimpse pandas based version with unnecessary list comprehension. Fixed that too.
> glimpse polars engine

- src/pytimetk/core/frequency.py
The changes are:
* I included the 'A-DEC' type as 'Y'.
* I included `force_regular` parameter on `get_frequency_summary`
> [refactor]: include `force_regular` parameter on `get_frequency_summary`

- src/pytimetk/core/frequency.py
- tests/test_get_frequency_summary.py
In this PR I included: 
* New frequency option: Q-DEC as Q and W-SUN as W
* Tests for the most common frequency options: D, W, M, Q and Y.
> [test]: Include tests for `get_frequency_summary()`

- src/pytimetk/__init__.py
- src/pytimetk/feature_engineering/__init__.py
- src/pytimetk/feature_engineering/wavelet.py
#51 More Augment Functions: wavelet
Updated _init_ files for wavelet transform
> Wavelet init

- src/pytimetk/feature_engineering/holiday_signature.py
augment_holiday polars engine, also started to add in memory_reduction for the pandas side. This will keep memory under control and keep things moving fast.
> augment_holiday polars engine

- src/pytimetk/feature_engineering/holiday_signature.py
holiday_signature.py get_holiday polars engine
> holiday_signature.py get_holiday polars engine

- src/pytimetk/feature_engineering/leads.py
> leads mem optimized

- src/pytimetk/feature_engineering/timeseries_signature.py
timeseries_signature mem optimized
> timeseries_signature mem optimized

- src/pytimetk/core/frequency.py
docstring fix for get_frequency_summary
> Update frequency.py docstring fix for get_frequency_summary

- src/pytimetk/core/frequency.py
optimized get_pandas_freq with mapping rather than many ifs. Also this makes it way easier to maintain and add to if needed.
> Update frequency.py get_pandas_freq mapping

- src/pytimetk/core/frequency.py
Quick update on seconds for min and max quarterly seconds.
> Justin kurland quarterly second patch

- src/pytimetk/feature_engineering/wavelet.py
> wavelet mem optimization

- src/pytimetk/core/anomalize.py
- src/pytimetk/core/apply_by_time.py
> anamolize mem optiimization

- src/pytimetk/core/anomalize.py
- src/pytimetk/core/apply_by_time.py
apply by time.py mem optimization
> Justin kurland apply by time.py mem optimization

- src/pytimetk/core/future.py
> future mem optimized

- src/pytimetk/core/anomalize.py
- src/pytimetk/feature_engineering/lags.py
> Update anomalize.py cleaned docstring

- src/pytimetk/core/frequency.py
- tests/test_get_trend_frequency.py
In this PR I have:
* included engine parameter on get_trend_frequency()
* added force_regular parameter to get_frequency_summary()
* included the tests
> [feature]: Included polars engine on `get_trend_frequency()`

- docs/guides/06_anomalize.qmd
adding guide for `anomalize` functions
> added guide for anomalize

- docs/guides/06_anomalize.qmd
Fixing a typo in the iqr_alpha callout
> fix type in iqr_alpha callout
