business-science/pytimetk

- tk_augment_time.py
First effort to duplicate original R timetk functionality for automated date time feature engineering. Currently there are 30 date time features in the function. Some effort was made to align with original timetk functionality for date time feature engineering, however some additional features were also added to account for additional time-specific features that occur at smaller temporal units of analysis, e.g., seconds, microseconds, nanoseconds, as well as some additional business-specific features related to the workweek, and business cycles, etc.
> Adding tk_augment_time

- docs/getting-started/01_installation.qmd
Just removing (surely) a typo in the installation of timetk and dependencies using poetry.
It is currently written: 
`pip install poetry`.
So I've changed it to `poetry install`
> correct timetk installation command with poetry

- docs/guides/04_wrangling.qmd
Creating some examples for `summarize_by_time()` and `future_frame()`
> add examples for summarize_by_time and future_frame

- src/timetk/core/summarize_by_time.py
I believe when `kind = "period"` that the resampling and aggregation converts the date column to period. Therefore, any period conversion thereafter will throw an error.
> Fix: remove duplicate conversion to period

- src/timetk/core/pad.py
- tests/test_pad_by_time.py
Addressed issue #37.
Pad By Time Grouped - End Behavior 
This fix adds an input variable:global_group_max which allows users to select if they want to use the global max or local max when deciding the end time to use for padding.
> Pad By Time Grouped - End Behavior #37

- src/timetk/core/pad.py
- tests/test_pad_by_time.py
New behavior to mimic to R package.
start_date : str, optional
Specifies the start of the padded series.  If NULL, it will use the lowest value of the input variable. In the case of groups, it will use the lowest value by group.
end_date  : str, optional;
Specifies the end of the padded series.  If NULL, it will use the highest value of the input variable.  In the case of groups, it will use the highest value by group.
Also updated the test_pad_by_time file to account for changes
> Updated parameter to start_date and end_date

- src/pytimetk/core/rolling.py
Change window method of rolling_apply_2 to be consistent with pd.rolling
1) 
Before: Right biased if even sized window.
Fix: Left biased window if even sized window.
2) 
Before: NaN if min_period < window.
Fix: Allow for value calculation if min_period < window size.
> Fix: consistent rolling window between pd.rolling and rolling_apply_2

- src/pytimetk/core/rolling.py
**Proposing an overhaul of the augment functions to be able to handle all variety of window function types in one call.**
- Introduced `window_func` and `window_func_with_iv` to cleanly separate Series-based and DataFrame-based rolling functions.
- Removed `use_independent_variables` argument, enhancing function flexibility.
- Allows for diverse window function types in one call eliminating the need to make multiple augment calls and dataframe concatenations to get all desired augmented features.
**Example of the type of call that would be possible:**
```
rolled_df = (
df.augment_rolling(
date_column = 'date', 
value_column = ['value1', 'value2', 'value3'], 
window=[2, 4],
window_func = [
'mean',
'std',
('sample_std', lambda x: sample_std(x)),
('pop_std', lambda x: population_std(x))
], …
```
> Overhaul augment_rolling to streamline window function handling

- src/pytimetk/core/ts_features.py
- tests/test_ts_features.py
I made a few refactors here:
* I moved the variable `group_names` to prevent overwriting.
* Instead of using `data = data.copy()`, I now use `df = data.obj.copy()` because I need to verify at the end of the code whether `data` is a data frame or a grouped data frame.
* I created `construct_df` for non-grouped data frames.
* I applied the `ts_features` function to both data frames and grouped data frames.
* I included  `dropna` in the result of `ts_features`. These columns are not applied to non-grouped data frames.
* I included some tests.
> [Refactor]:  specifying features for dataframe and grouped dataframes

- pyproject.toml
- src/pytimetk/core/summarize_by_time.py
Created the new pattern for `summarize_by_time` that now incorporates the `engine` parameter where users will be able to select between `pandas` and `polars`.  
If successful and we like the pattern we can now extend this across all current and future functions.
> summarize_by_time engine

- src/pytimetk/core/expanding.py
- src/pytimetk/utils/polars_helpers.py
- Enable users to pass specific parameters to `qt_quantile` within `augment_expanding`
- Involves more complicated error handling for passing tuples to maintain consistent tuple user experience
- Added `pl_quantile` to `utils.polars_helpers`, but can decide later on the best place for it
> feat(augment_expanding): add configurable qt_quantile

- src/pytimetk/utils/datetime_helpers.py
Cleaned up `freq_to_dateoffset` to make cleaner, more efficient, readable, extendable, and Pythonic. Changed to primarily be a lookup table/map dict type function rather than a series of if, else, elif statements.
> Update datetime_helpers.py - freq_to_dateoffset

- src/pytimetk/core/pad.py
Quick there was not alignment between the singular series/dataframe and the group based pad. In the singular instance there was a need for further wrangling to forward fill names, while for the group based pad this was taken care of. 
I used a simple trick to find the column with 0 variance, to isolate in the event that this column exists and automatically forward fill this. Now there is alignment for this pandas version.
> pandas pad 

- src/pytimetk/core/fourier.py
Hi, 
Let me know your thoughts about this implementation. 
I think it is what was expected. With order 1 (k=1) I got the same results than the current function. 
I only implemented the function for the DataFrames, and if it is validated it will be straightforward to do the same for the groups. 
I would also like to replace those for loops, but for the moment I was more interested in the correctness of the results :)
fix  #22 
NB this is a working version. I implemented my fix in a _v2 function so that the other function still works :)
> Augment fourier - dataframes only

- src/pytimetk/feature_engineering/wavelet.py
#51 More Augment Functions: wavelet
Implemented 3 variation of wavelet transforms
1. Morlet Complex Wavelet
2. Bump Wavelet
3. Analytic Morlet Complex Wavelet
Currently only the pandas engine is deployed.  Will start exploring a polars implementation. 
_init_ files in separate PR.
> #51 More Augment Functions - Wavelet Transform

- src/pytimetk/core/frequency.py
- tests/test_get_seasonal_frequency.py
In this PR I have:
* included `engine` parameter on `get_seasonal_frequency`
* fixed `time_scale_template` to return `median_unit` as the index when using polars. Now `time_scale_template` returns the same result when using polars or pandas
* added `force_regular` to `get_frequency_summary`
* included the tests
> [feature]: include polars engine on `get_seasonal_frequency`

- src/pytimetk/core/future.py
- src/pytimetk/feature_engineering/lags.py
- src/pytimetk/feature_engineering/leads.py
future frame on single series behavior was different than the groupby in the event that there is just a singular dataframe as opposed to a groupby so the name for a given id if present required the use of a lambda to forward fill. I have added to the function to do this automatically internally in the case there is an id column so it eliminates the need for lambda after the fact. I have updated the docstring accordingly as well.
> future frame forward fill internal

- pyproject.toml
I changed my email on pyproject.toml because dmmada is my personal email. The svm.macedo is what I use on github.
> Changed my email on pyproject.toml

- src/pytimetk/core/ts_summary.py
- src/pytimetk/feature_engineering/fourier.py
- tests/test_ts_summary.py
partially solves #77 
Done, tests working. Updated augment_fourier so that it uses this new version.
Part of it depends on the function "get_frequency_summary" so it is the next on my list :) In the meantime I computed this part like this: `frequency_summary = pl.from_pandas(get_frequency_summary(date.to_pandas()))`
> Ts summary - polars backend

- src/pytimetk/core/frequency.py
- src/pytimetk/utils/checks.py
Here is a first draft. 
It is working as is but I have two concerns: 
_get_pandas_frequency is difficult to convert because there is currently no idx.inferred_freq equivalent in polars.
The only solution I can think of is to write an equivalent of inferred_freq pandas implementation, but I am not sure if it is worth the time.
I don't know what unit is expected for freq_median_timedelta. 
Again, there is no timedelta in polars so I create it from _freq_median_seconds and put the unit to seconds. 
But the output is probably not consistent with the pandas implementation then ? 
Linked to #77
> add polars backend to get_frequency_summary - first draft

- src/pytimetk/core/filter_by_time.py
Hi @mdancho84, adding a v1 of filter by time. See notes below and let me know what you think.
* **Inupts:** Current user inputs include `data`, `date_column`, `start_date`, `end_date` and `engine`
* **Date Parsing:** For the `start_date` and `end_date` inputs, I used the length of the input to determine whether it is a date, date/month, year, etc. I'm not sure if this is the best method determine how to parse and filter the dates. See screenshot below - 
* **Groups:**  I'm not sure if I implemented the grouping functionality properly as the index looks weird with groups.  I was also wondering if a function like this requires groups. Technically, any filtering by date, will automatically filter each group.
* **Engine:** Currently only `Pandas`. However I used the same format for the other …
> add filter_by_time
